# Generated by Django 4.0.6 on 2022-07-14 01:46

import applications.vending_machine.models.model_validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(choices=[(5, '5 cents'), (10, '10 cents'), (20, '20 cents'), (50, '50 cents'), (100, '100 cents')], validators=[applications.vending_machine.models.model_validations.multiple_of_5]),
        ),
    ]
