# Generated by Django 4.0.6 on 2022-07-15 00:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_available', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='vending_machine.product')),
            ],
            options={
                'verbose_name': 'Product Audit',
                'verbose_name_plural': 'Product Audits',
                'ordering': ['created_at'],
            },
        ),
    ]
